# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 03:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256, verbose_name='Ответ')),
                ('votes', models.IntegerField(default=0, verbose_name='Голосов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'ordering': ['question', 'created'],
                'verbose_name_plural': 'Ответы',
                'db_table': 'answers',
                'verbose_name': 'Ответ',
            },
        ),
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=256, verbose_name='Тип')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Типы ответов',
                'db_table': 'AnswerTypes',
                'verbose_name': 'Тип ответа',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.CharField(max_length=64, verbose_name='Опрос')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'ordering': ['created'],
                'verbose_name_plural': 'Опросы',
                'db_table': 'interview',
                'verbose_name': 'Опроса',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.AnswerType', verbose_name='Тип ответа')),
                ('interview', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_app.Interview', verbose_name='Опрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['created', 'interview'],
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='VotesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Answer')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'interview'],
                'verbose_name_plural': 'Результаты опроса',
                'db_table': 'Votes_Result',
                'verbose_name': 'Результат опроса',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Question', verbose_name='Вопрос'),
        ),
    ]
